channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=21.4.0
  - beautifulsoup4=4.12.2
  - blinker=1.5
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - commonmark=0.9.1
  - dataclasses=0.8
  - docutils=0.19
  - feedgenerator=2.0.0
  - future=0.18.3
  - ghp-import=2.1.0
  - importlib-metadata=6.6.0
  - jinja2=3.0.3
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - markdown=3.4.3
  - markupsafe=2.1.2
  - mdurl=0.1.0
  - ncurses=6.3
  - openssl=3.1.0
  - pelican=4.8.0
  - pip=21.3.1
  - pygments=2.14.0
  - python=3.10.10
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2023.3
  - readline=8.2
  - rich=13.2.0
  - setuptools=67.7.2
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - sqlite=3.38.5
  - tk=8.6.12
  - typing_extensions=4.1.1
  - tzdata=2023c
  - unidecode=1.3.6
  - wheel=0.37.1
  - xz=5.2.6
  - zipp=3.6.0
  - zlib=1.2.13
  - pip:
      - markdown-it-py==2.2.0
      - pelican-resume==0.1.0
